Added Products Page
munjalSaksham71/Regal-Store pull request #1
Opened 2022-03-14 08:46 UTC by munjalSaksham71

Till Now: every Thing is Static - Pending: Functionality to Filters

here are the screenshots: 
<img width="1431" alt="Screenshot 2022-03-14 at 2 14 58 PM" src="https://user-images.githubusercontent.com/75904883/158136176-6d913ad4-a0fe-4863-b768-c633be633bb2.png">
<img width="1438" alt="Screenshot 2022-03-14 at 2 15 17 PM" src="https://user-images.githubusercontent.com/75904883/158136232-cae95815-6935-4349-ab9b-fefe6610d910.png">

2022-03-14 18:29 UTC, tusharkandpal requested changes
Please make suggested changes.

2022-03-14 18:29 UTC, tusharkandpal commented on src/components/Card/Card.jsx
> +  const { title, categoryName, brand, imageUrl, price } = product.product;
Destructure it like  `Card( { title, categoryName } )` or simple use `Card( props )`

2022-03-14 18:29 UTC, tusharkandpal commented on src/components/ProductListing/ProductListing.js
> +const ProductListing = (products) => {
Please correct here too.

2022-03-14 18:29 UTC, tusharkandpal commented on src/context/product-context.js
> +            return {...state, products: action.payload, loading: false, error: ''};
No need to set the keys which are not changing in a case like `error` here

2022-03-14 18:29 UTC, tusharkandpal commented on src/context/product-context.js
> +            return {...state, products: [], loading: false, error: "Something went wrong"};
here `products`

2022-03-14 18:29 UTC, tusharkandpal commented on src/context/product-context.js
> +const Product = createContext();
Better to use `ProductContext` as per naming convention.

2022-03-15 15:27 UTC, mariyasada approved these changes

2022-03-15 15:27 UTC, mariyasada commented on src/context/product-context.js
> +}
Is there any specific reason to use useReducer Here?

2022-03-15 15:33 UTC, tusharkandpal approved these changes

2022-03-15 18:02 UTC, tusharkandpal requested changes
one more suggestion, please work on it

2022-03-15 18:02 UTC, tusharkandpal commented on src/context/product-context.js
> +        axios.get('/api/products')
use `async-await` for api calls

2022-03-16 04:47 UTC, munjalSaksham71 commented on src/context/product-context.js
> +}
I am using useReducer here - just to maintain the state

2022-03-16 04:47 UTC, munjalSaksham71 commented on src/context/product-context.js
> +        axios.get('/api/products')
Ok i ll do it now.

2022-03-16 08:49 UTC, tusharkandpal requested changes
This is not the right way. Either create IIFE or a separate function to call api inside it.

2022-03-16 09:06 UTC, tusharkandpal approved these changes
All good! 👍

2022-03-16 09:06 UTC, merged